apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mku2zglek-nodejs
  janus-idp.io/tekton: mku2zglek-nodejs
  backstage.io/kubernetes-id: mku2zglek-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mku2zglek-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
